### PR TITLE
Documentation improvements and task fixes

### PR DESCRIPTION
**Pull request by jalaziz**
The commit to remove the check for failed setup is required if we're not setting both the hostname and policy as the registered variable will be for the last (skipped) task and won't contain stderr.

The play will fail anyway since we're not ignoring errors, so non-zero result codes will result in the task failing.

If we really want to display a more friendly message, two solutions that come to mind are:

1. Use different variables and check if each was skipped, and if not, what the result code or output was.
2. Use one command with inline conditionals to include the appropriate options

In both cases, you'll want to add "ignore_errors: true" to the task(s).

### CODE REVIEW

**Comment by jalaziz** [comment]
Also, if you actually want the role name to be just threatstack instead of threatstack-ansible. I _believe_ you need to provide an alternative name to the role on galaxy.

**Comment by jalaziz** [comment]
@apollocatlin Any updates on this PR? I can also just use my fork, but would prefer to use the official role.

**Comment by apollocatlin** [comment]
Ah yes, sorry I will be updating in next 24.

**Comment by jalaziz** [comment]
No worries, if you want to change the role name, I can revert my changes to the documentation.

**Comment by apollocatlin** [comment]
I fixed the naming outside of the pull request.
https://galaxy.ansible.com/list#/roles/3018

Thank you for the pointer there. Getting the defaults in and changing the error checking now.

**Comment by jalaziz** [comment]
Thanks!

**Comment by apollocatlin** [comment]
fixing in https://github.com/threatstack/threatstack-ansible/pull/3

just due to some timing changes.

**Pull request closed without merging**
