### PR TITLE
cloudsight_setup task Agent config

### PR DESCRIPTION
**Pull request by OldCrowEW**
Add task to run Agent config if threatstack_agent_optional_configs is defined and has a value

### CODE REVIEW

**Comment by benpatterson** [comment]
@OldCrowEW Thanks for posting a potential fix. Sounds like it might be a fix for #58 ?

If you have a valid deployment key, you may be able to set that in your travis settings for your branch and re-run tests. That env value would be [here](https://github.com/threatstack/threatstack-ansible/blob/master/tests/test.yml#L6), I believe. If you don't want to go that route, I can open up a branch on our side so tests can run all the way through.

**Comment by OldCrowEW** [comment]
> @OldCrowEW Thanks for posting a potential fix. Sounds like it might be a fix for #58 ?
> 
> If you have a valid deployment key, you may be able to set that in your travis settings for your branch and re-run tests. That env variable would be [here](https://github.com/threatstack/threatstack-ansible/blob/master/tests/test.yml#L6), I believe. If you don't want to go that route, I can open up a branch on our side so tests can run all the way through.

Im not sure how do that. Do you have a doc explaining this? 

> @OldCrowEW Thanks for posting a potential fix. Sounds like it might be a fix for #58 ?
> 
> If you have a valid deployment key, you may be able to set that in your travis settings for your branch and re-run tests. That env variable would be [here](https://github.com/threatstack/threatstack-ansible/blob/master/tests/test.yml#L6), I believe. If you don't want to go that route, I can open up a branch on our side so tests can run all the way through.

If you dont mind that would be awesome if you took over my branch. I dont want to accidentally commit our deployment key :D

**Comment by OldCrowEW** [comment]
> @OldCrowEW Thanks for posting a potential fix. Sounds like it might be a fix for #58 ?

The issue you linked appears to be around installing the agent without activating it. This is to create a `cloudsight config` task to run `when: threatstack_agent_optional_configs is defined`.

**Comment by benpatterson** [comment]
Och my fault on linking tickets. I was thinking of #50, but even so, I see that your situation is a bit different (indeed, different variable, and different timing of the scenario in certain situations). In any case, I think I have the context now.

Indeed there are ways you can run this on your own, but it'll be easier if I just take this branch and create a sibling on our (root) repo. I'll put in a cycle on that this afternoon.

**Comment by benpatterson** [comment]
@OldCrowEW the GH tests have passed when I ran them from our parent project.

Still want to run a couple of end-to-end tests to verify it's good to go. We can put that on me for now. Hoping to get to it next week.

**Comment by benpatterson** [comment]
@OldCrowEW I've been looking at this (read:testing). Wanted to ask you: are you trying to fix this for the 1.x series of agents? There are two separate files (one for 1.x and the other for 2.x). Thought I'd check back on that as I look at it....

Cheers

**Comment by benpatterson** [comment]
Hm, I'm wondering if you can get what you want if you instead set `threatstack_agent_config_args`, because there is a task dedicated to this purpose a bit further down in the file. I wonder why that might not be getting you what you need?

(And again to emphasize, this pathway is only executed on 1.x agents.)

**Comment by OldCrowEW** [comment]
Closing as we no longer need.

**Pull request closed without merging**
