### PR TITLE
Support for threatstack_hostname

### PR DESCRIPTION
**Pull request by benpatterson**
Starting a new PR with the associated commits in order to test on the Travis infrastructure, and put in some additional improvements while we're here.

### CODE REVIEW

**Comment by benpatterson** [comment]
I have to see what's up with travis failing, but with these changes, tests are passing "locally" aka on vagrant.

I have to put this down for now but hope to get back to it next week. Feel free to add your thoughts; otherwise I'll put in a cycle to sort out the travis failures.

**Comment by benpatterson** [comment]
Alright @sixth I think we are gtg.

CC @olhado in case he has comments/thoughts. Otherwise I'll plan on merging in the next day or 2.

**Comment by sixth** [comment]
LGTM

**Comment by benpatterson** [comment]
thx for the feedback and the PR itself :tada: 
merging

**Pull request merged**
